### ISSUE TITLE
store: Segmentation fault

### ISSUE THREAD

**Issue by aardes** [TileDB-Inc/TileDB-VCF#428] opened 2022-04-13 14:08 UTC
Dear,

I tried to add the dbSNP vcf file to the TileDB-VCF.

but I go the following error:
Segmentation fault

Here is the header of the file:
```
##fileformat=VCFv4.2
##fileDate=20210513
##source=dbSNP
##dbSNP_BUILD_ID=155
##reference=GRCh38.p13
##fileformat=VCFv4.2
##fileDate=20210513
##phasing=partial
##INFO=<ID=RS,Number=1,Type=Integer,Description="dbSNP ID (i.e. rs number)">
##INFO=<ID=GENEINFO,Number=1,Type=String,Description="Pairs each of gene symbol:gene id.  The gene symbol and id are delimited by a colon (:) and each pair is delimited by a vertical bar (|).  Does not include pseudogenes.">
##INFO=<ID=PSEUDOGENEINFO,Number=1,Type=String,Description="Pairs each of pseudogene symbol:gene id.  The pseudogene symbol and id are delimited by a colon (:) and each pair is delimited by a vertical bar (|)">
##INFO=<ID=dbSNPBuildID,Number=1,Type=Integer,Description="First dbSNP Build for RS">
##INFO=<ID=SAO,Number=1,Type=Integer,Description="Variant Allele Origin: 0 - unspecified, 1 - Germline, 2 - Somatic, 3 - Both">
##INFO=<ID=SSR,Number=1,Type=Integer,Description="Variant Suspect Reason Codes (may be more than one value added together) 0 - unspecified, 1 - Paralog, 2 - byEST, 4 - oldAlign, 8 - Para_EST, 16 - 1kg_failed, 1024 - other">
##INFO=<ID=VC,Number=1,Type=String,Description="Variation Class">
##INFO=<ID=PM,Number=0,Type=Flag,Description="Variant has associated publication">
##INFO=<ID=NSF,Number=0,Type=Flag,Description="Has non-synonymous frameshift A coding region variation where one allele in the set changes all downstream amino acids. FxnClass = 44">
##INFO=<ID=NSM,Number=0,Type=Flag,Description="Has non-synonymous missense A coding region variation where one allele in the set changes protein peptide. FxnClass = 42">
##INFO=<ID=NSN,Number=0,Type=Flag,Description="Has non-synonymous nonsense A coding region variation where one allele in the set changes to STOP codon (TER). FxnClass = 41">
##INFO=<ID=SYN,Number=0,Type=Flag,Description="Has synonymous A coding region variation where one allele in the set does not change the encoded amino acid. FxnCode = 3">
##INFO=<ID=U3,Number=0,Type=Flag,Description="In 3' UTR Location is in an untranslated region (UTR). FxnCode = 53">
##INFO=<ID=U5,Number=0,Type=Flag,Description="In 5' UTR Location is in an untranslated region (UTR). FxnCode = 55">
##INFO=<ID=ASS,Number=0,Type=Flag,Description="In acceptor splice site FxnCode = 73">
##INFO=<ID=DSS,Number=0,Type=Flag,Description="In donor splice-site FxnCode = 75">
##INFO=<ID=INT,Number=0,Type=Flag,Description="In Intron FxnCode = 6">
##INFO=<ID=R3,Number=0,Type=Flag,Description="In 3' gene region FxnCode = 13">
##INFO=<ID=R5,Number=0,Type=Flag,Description="In 5' gene region FxnCode = 15">
##INFO=<ID=GNO,Number=0,Type=Flag,Description="Genotypes available.">
##INFO=<ID=PUB,Number=0,Type=Flag,Description="RefSNP or associated SubSNP is mentioned in a publication">
##INFO=<ID=FREQ,Number=.,Type=String,Description="An ordered list of allele frequencies as reported by various genomic studies, starting with the reference allele followed by alternate alleles as ordered in the ALT column. When not already in the dbSNP allele set,
 al
leles from the studies are added to the ALT column.  The minor allele, which was previuosly reported in VCF as the GMAF, is the second largest value in the list.  This is the GMAF reported on the RefSNP and EntrezSNP pages and VariationReporter">
##INFO=<ID=COMMON,Number=0,Type=Flag,Description="RS is a common SNP.  A common SNP is one that has at least one 1000Genomes population with a minor allele of frequency >= 1% and for which 2 or more founders contribute to that minor allele frequency.">
##INFO=<ID=CLNHGVS,Number=.,Type=String,Description="Variant names from HGVS.    The order of these variants corresponds to the order of the info in the other clinical  INFO tags.">
##INFO=<ID=CLNVI,Number=.,Type=String,Description="Variant Identifiers provided and maintained by organizations outside of NCBI, such as OMIM.  Source and id separated by colon (:).  Each identifier is separated by a vertical bar (|)">
##INFO=<ID=CLNORIGIN,Number=.,Type=String,Description="Allele Origin. One or more of the following values may be summed: 0 - unknown; 1 - germline; 2 - somatic; 4 - inherited; 8 - paternal; 16 - maternal; 32 - de-novo; 64 - biparental; 128 - uniparental; 256 - not
-te
##INFO=<ID=CLNSIG,Number=.,Type=String,Description="Variant Clinical Significance, 0 - Uncertain significance, 1 - not provided, 2 - Benign, 3 - Likely benign, 4 - Likely pathogenic, 5 - Pathogenic, 6 - drug response, 8 - confers sensitivity, 9 - risk-factor, 10 -
 as
##INFO=<ID=CLNDISDB,Number=.,Type=String,Description="Variant disease database name and ID, separated by colon (:)">
##INFO=<ID=CLNDN,Number=.,Type=String,Description="Preferred ClinVar disease name">
##INFO=<ID=CLNREVSTAT,Number=.,Type=String,Description="ClinVar Review Status: no_assertion - No asserition provided by submitter, no_criteria - No assertion criteria provided by submitter, single - Classified by single submitter, mult - Classified by multiple sub
mit
##INFO=<ID=CLNACC,Number=.,Type=String,Description="For each allele (comma delimited), this is a pipe-delimited list of the Clinvar RCV phenotype accession.version strings associated with that allele.">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  dbSNP
```

For your information, I the 2 columns (FORMAT  dbSNP)  with fixed values to the original data because I thought that could be the issue

so here is the data look like:

`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  dbSNP
NC_000001.11    10001   rs1570391677    T       A,C     .       .       RS=1570391677;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9891,0.0109,.|SGDP_PRJ:0,1,.|dbGaP_PopFreq:1,.,0;COMMON       GT:GQ:DP        0/1:35:4
NC_000001.11    10002   rs1570391692    A       C       .       .       RS=1570391692;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9944,0.005597 GT:GQ:DP        0/1:35:4
NC_000001.11    10003   rs1570391694    A       C       .       .       RS=1570391694;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9902,0.009763 GT:GQ:DP        0/1:35:4
NC_000001.11    10007   rs1639538116    T       C,G     .       .       RS=1639538116;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=dbGaP_PopFreq:1,0,0     GT:GQ:DP        0/1:35:4
NC_000001.11    10008   rs1570391698    A       C,G,T   .       .       RS=1570391698;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9969,.,0.003086,.|dbGaP_PopFreq:1,0,.,0       GT:GQ:DP        0/1:35:4
NC_000001.11    10009   rs1570391702    A       C,G     .       .       RS=1570391702;dbSNPBuildID=154;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=KOREAN:0.9911,.,0.008916|dbGaP_PopFreq:1,0,0   GT:GQ:DP        0/1:35:4
NC_000001.11    10013   rs1639538192    T       C,G     .       .       RS=1639538192;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=dbGaP_PopFreq:1,0,0     GT:GQ:DP        0/1:35:4
NC_000001.11    10013   rs1639538231    TA      T       .       .       RS=1639538231;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=INDEL;R5;GNO;FREQ=dbGaP_PopFreq:1,0     GT:GQ:DP        0/1:35:4
NC_000001.11    10014   rs1639538207    A       C,G,T   .       .       RS=1639538207;SSR=0;PSEUDOGENEINFO=DDX11L1:100287102;VC=SNV;R5;GNO;FREQ=dbGaP_PopFreq:1,0,0,0   GT:GQ:DP        0/1:35:4`

the original data can be found here: https://ftp.ncbi.nih.gov/snp/archive/b155/VCF/

Could you please check this.

thanks in advance
Amin

**Comment by aaronwolen** [comment] 2022-04-14 15:40
Hi @aardes, could you provide the version of tiledbvcf you were using when the segfault occured?

You can retrieve version from the CLI with:

```sh
tiledbvcf version
```

and the Python package with:

```py
import tiledbvcf
tiledbvcf.version
```

**Comment by aardes** [comment] 2022-04-19 08:21
@aaronwolen Thanks for the follow up and sorr for the delay, 

TileDB-VCF version 5565e72-modified
TileDB version 2.3.3
htslib version 1.12


I checked another issue track and learned a bit more about my error, I think the issue is related to the naming of the contigs.

in the file that I have the chromosome names are different from the usual 1,2, .. or chr1,chr2, ...,

I am trying to update the names and test it. I will keep you posted. 

thanks

**Comment by aaronwolen** [comment] 2022-04-22 13:47
HI @aardes, that version is quite out of date. Could you try installing the latest version of tiledbvcf (0.14.0)? We've significantly improved support for ingesting sample-less VCF files such as those distributed by dbGAP. We'll run some tests on our end to verify.

**Comment by ckrilow** [comment] 2022-04-22 19:43
Hi @aardes. I was able to ingest the following VCF file, https://ftp.ncbi.nih.gov/snp/archive/b155/VCF/GCF_000001405.39.gz, into a TileDB array without issue.  Currently, I am using the following tiledbvcf version that was built via Anaconda:
```
TileDB-VCF version 0b4cabd-modified
TileDB version 2.8.1 
htslib version 1.15.1
```
When you get a chance, can you please update your tiledbvcf to the most current version and re-try the data ingestion?

**Comment by aaronwolen** [comment] 2022-04-29 20:23
Closing this for now since it appears the issue is resolved in the latest version of tiledbvcf.

**Closed** 2022-04-29 20:23 UTC
